### PR TITLE
add task1,2 and images

### PR DESCRIPTION
**Pull request by ciciecho-ds**

### CODE REVIEW

**Comment by nobbynguyen** [comment]
@ciciecho-ds : just 2 minor comments, should we
- Task 3: move the link to the notebook to next line, highlight the link so it's more eye-catching for TA to grade.
- Task 4: highlight the link also.

**Comment by ciciecho-ds** [comment]
> @ciciecho-ds : just 2 minor comments, should we
> 
> * Task 3: move the link to the notebook to next line, highlight the link so it's more eye-catching for TA to grade.
> * Task 4: highlight the link also.

I haven't added anything for 3 and 4.

**Review by gauthampughazhendhi — APPROVED** [review]
Looks good to me

**Comment by nobbynguyen** [comment]
> > @ciciecho-ds : just 2 minor comments, should we
> > 
> > * Task 3: move the link to the notebook to next line, highlight the link so it's more eye-catching for TA to grade.
> > * Task 4: highlight the link also.
> 
> I haven't added anything for 3 and 4.

Oh sorry, I misunderstood.

**Review by nobbynguyen — APPROVED** [review]

**Pull request merged**
