### PR TITLE
Add screenshot

### PR DESCRIPTION
**Pull request by nobbynguyen**

### CODE REVIEW

**Comment by nd265** [comment]
Hi @nobbynguyen , could you move the first screenshot under S3 bucket towards the end of notebook? When we save the csv file using python, after that? 
Also, one more change, in the first set of screenshots, IP addresses are visible for Cici, Gautham and yours, in the instance screenshot, could you hide/mask them? As in the instructions, it is mentioned that no IP should be visible. 
I think one screenshot suffices per task, so your work of masking IPs for task 1 will be saved

**Comment by nobbynguyen** [comment]
Gotcha and fixed.

**Review by nd265 — APPROVED** [review]

**Comment by gauthampughazhendhi** [comment]
@nobbynguyen  Are the screenshot links working?

**Review by gauthampughazhendhi — COMMENTED** [review]
Thanks for the goodwork

**Pull request merged**
